### ISSUE TITLE
BCHP metric bug

### ISSUE THREAD

**Issue by yaseenkhanmohmand** [brtr/nft-hunter#8]
[](https://user-images.githubusercontent.com/34256008/163115146-77604623-6e88-4c36-a0da-3448d22035c7.png)When calculating the BCHP metric the formula is:

Number of holders that hold atleast one Blue chip project (excluding the bluechip project in questions*)/
total number of holders.

attaching image of the error:
image
![image](https://user-images.githubusercontent.com/34256008/163225250-bc2039b2-8f79-4fea-8b0d-d62704e6cc90.png)

The percentage on Azuki should not be 100%, we should not be counting the number of holders that hold azuki when calculating this percentage for azuki.

**Comment by iannono** [comment]
@yaseenkhanmohmand 
<img width="1339" alt="截屏2022-04-14 上午9 31 51" src="https://user-images.githubusercontent.com/1317465/163296348-11e7a2ad-6492-4c41-95cb-b0cc79e0030d.png">

This had been fixed by removing self holders.

Please check.

**Comment by yaseenkhanmohmand** [comment]
Looks good Thank you!
